name: 03 - Workflow Runners

on:
    push:

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This is running on Ubuntu"
                echo "OS: $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                echo "This is running on Windows"
                echo "OS: $RUNNER_OS"
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: |
                echo "This is running on MacOS"
                echo "OS: $RUNNER_OS"
                