name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug}}

on:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
env:
    MY_WORKFLOW_VAR: "workglow_variable_value"
    MY_OVERWRITTEN_VAR: "workflow_value"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: "job_variable_value"
            MY_OVERWRITTEN_VAR: "job_value"
        steps:
            - name: Display Information
              run: |
                echo "Event Name:${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number }}"
            - name: Retrieve Variable
              run: |
                echo "Variable MY_VAR is set to: ${{ vars.MY_VAR }}"
            - name: Print Env Variable
              env:
                MY_OVERWRITTEN_VAR: "step"
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: Print Env Variables
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
    echo-data2:
        runs-on: ubuntu-latest
        steps:
            - name: Print Env Variables
              run: |
                echo "Workflow env: $env.MY_WORKFLOW_VAR"
                echo "Overwritten env: $env.MY_OVERWRITTEN_VAR"