name: 07 - Expressions

on:
    push:
    workflow_dispatch:
        inputs:
            dubug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print Start-Up Data'
              run: |
                echo "Triggering Event: ${{ github.event_name }}"
                echo "Branch/Tag Ref: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"