name: 15 - Matrices

on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{ matrix.node-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
                include: 
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
        steps: 
            - name: Setup Node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{ matrix.node-version }}
            - name: Fail If Experimental
              if: matrix.tag == 'experimental'
              run: exit 1
            - name: Perform Some Test
              run: echo "Running tests on Node.js version ${{ matrix.node-version }} on OS ${{ matrix.os }}"

    include-example:
        name: ${{ matrix.color }} - ${{ matrix.shape }} - ${{ matrix.size }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color: [red, green]
                shape: [circle, square]
                size: [small, large]
                inlude:
                    - color: red
                      shape: triangle
        steps: 
            - name: Display Combination
              run: echo "${{ matrix.color }} - ${{ matrix.shape }} - ${{ matrix.size }}"
        