name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS | BB - ${{ inputs.base_branch }} - TB - ${{ inputs.target_branch }} - WD - ${{ inputs.working_directory }}

on:
    workflow_dispatch:
        inputs:
            base_branch:
                type: string
                default: main
            target_branch: 
                type: string
                default: update-dependencies
            working_directory:
                type: string
                default: 17-custom-actions/react-app

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check for dependency updates
              uses: ./.github/actions/js-dependency-update
              with:
                    base-branch: ${{ inputs.base_branch }}
                    target-branch: ${{ inputs.target_branch }}
                    working-directory: ${{ inputs.working_directory }}