name: 17 - 3 - Custom Actions - Docker

on:
    workflow_dispatch:
        inputs:
            url:
                type: string
                default: 'https://www.google.com'
            max_trials:
                description: 'Maximum number of ping attempts'
                default: '10'
                required: false
            deplay:
                description: 'Delay between ping attempts in seconds'
                default: '10'
                required: false

jobs: 
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              with:
                  url: ${{ inputs.url }}
                  max_trials: ${{ inputs.max_trials }}
                  deplay: ${{ inputs.deplay }}